interface Country {
  value: string;
  label: string;
}

export const COUNTRIES: Country[] = [
  { value: "AF", label: "Afeganistão" },
  { value: "ZA", label: "África do Sul" },
  { value: "AL", label: "Albânia" },
  { value: "DE", label: "Alemanha" },
  { value: "AD", label: "Andorra" },
  { value: "AO", label: "Angola" },
  { value: "SA", label: "Arábia Saudita" },
  { value: "DZ", label: "Argélia" },
  { value: "AR", label: "Argentina" },
  { value: "AU", label: "Austrália" },
  { value: "AT", label: "Áustria" },
  { value: "BE", label: "Bélgica" },
  { value: "BO", label: "Bolívia" },
  { value: "BR", label: "Brasil" },
  { value: "BG", label: "Bulgária" },
  { value: "CA", label: "Canadá" },
  { value: "CL", label: "Chile" },
  { value: "CN", label: "China" },
  { value: "CO", label: "Colômbia" },
  { value: "KR", label: "Coreia do Sul" },
  { value: "CR", label: "Costa Rica" },
  { value: "HR", label: "Croácia" },
  { value: "DK", label: "Dinamarca" },
  { value: "EG", label: "Egito" },
  { value: "SV", label: "El Salvador" },
  { value: "AE", label: "Emirados Árabes Unidos" },
  { value: "SK", label: "Eslováquia" },
  { value: "SI", label: "Eslovênia" },
  { value: "ES", label: "Espanha" },
  { value: "US", label: "Estados Unidos" },
  { value: "EE", label: "Estônia" },
  { value: "PH", label: "Filipinas" },
  { value: "FI", label: "Finlândia" },
  { value: "FR", label: "França" },
  { value: "GR", label: "Grécia" },
  { value: "GT", label: "Guatemala" },
  { value: "NL", label: "Holanda" },
  { value: "HN", label: "Honduras" },
  { value: "HU", label: "Hungria" },
  { value: "IN", label: "Índia" },
  { value: "ID", label: "Indonésia" },
  { value: "IE", label: "Irlanda" },
  { value: "IS", label: "Islândia" },
  { value: "IL", label: "Israel" },
  { value: "IT", label: "Itália" },
  { value: "JP", label: "Japão" },
  { value: "LV", label: "Letônia" },
  { value: "LT", label: "Lituânia" },
  { value: "LU", label: "Luxemburgo" },
  { value: "MY", label: "Malásia" },
  { value: "MT", label: "Malta" },
  { value: "MA", label: "Marrocos" },
  { value: "MX", label: "México" },
  { value: "MZ", label: "Moçambique" },
  { value: "NG", label: "Nigéria" },
  { value: "NO", label: "Noruega" },
  { value: "NZ", label: "Nova Zelândia" },
  { value: "PA", label: "Panamá" },
  { value: "PY", label: "Paraguai" },
  { value: "PE", label: "Peru" },
  { value: "PL", label: "Polônia" },
  { value: "PT", label: "Portugal" },
  { value: "GB", label: "Reino Unido" },
  { value: "CZ", label: "República Checa" },
  { value: "DO", label: "República Dominicana" },
  { value: "RO", label: "Romênia" },
  { value: "SE", label: "Suécia" },
  { value: "CH", label: "Suíça" },
  { value: "TH", label: "Tailândia" },
  { value: "TW", label: "Taiwan" },
  { value: "TR", label: "Turquia" },
  { value: "UA", label: "Ucrânia" },
  { value: "UY", label: "Uruguai" },
  { value: "VE", label: "Venezuela" },
  { value: "VN", label: "Vietnã" },
];
